// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bindings is the struct registered with wails.Run as the bound App. Every
 * exported method becomes a callable in the frontend's wailsjs bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteScript removes a script by id.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteScript(id) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.DeleteScript", id);
}

/**
 * ExportCapture renders the request half of a traffic capture as a code
 * snippet. Empty client selects the target's default.
 * @param {number} id
 * @param {string} target
 * @param {string} client
 * @returns {$CancellablePromise<string>}
 */
export function ExportCapture(id, target, client) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ExportCapture", id, target, client);
}

/**
 * ExportTargets returns the snippet target catalog for the export dropdowns.
 * @returns {$CancellablePromise<$models.TargetView[]>}
 */
export function ExportTargets() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ExportTargets").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportWebhook renders a stored webhook delivery as a code snippet against
 * the relay's public ingress URL.
 * @param {string} project
 * @param {number} seq
 * @param {string} target
 * @param {string} client
 * @returns {$CancellablePromise<string>}
 */
export function ExportWebhook(project, seq, target, client) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ExportWebhook", project, seq, target, client);
}

/**
 * GetCapture returns one traffic capture with request/response headers and
 * bodies populated for the detail pane. Returns an error when the row is
 * absent (errors.Is, store.ErrNotFound).
 * @param {number} id
 * @returns {$CancellablePromise<$models.CaptureView>}
 */
export function GetCapture(id) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.GetCapture", id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetScript returns one script by id (the editor loads the full body on
 * selection). Wraps store.ErrNotFound when absent.
 * @param {number} id
 * @returns {$CancellablePromise<$models.ScriptView>}
 */
export function GetScript(id) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.GetScript", id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSettings returns the current configuration + registration state for the
 * settings screen. Missing config/credential files are not errors — the view
 * simply reflects defaults / "not registered". The config is re-read from
 * disk (not served from App's cache) so the form always shows what is
 * actually configured, including edits made outside the GUI while it runs.
 * @returns {$CancellablePromise<$models.SettingsView>}
 */
export function GetSettings() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.GetSettings").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetWebhook returns one webhook with body + headers populated for the detail
 * view and the replay form. Returns an error suitable for the frontend when the
 * row is absent (errors.Is, store.ErrNotFound).
 * @param {string} project
 * @param {number} seq
 * @returns {$CancellablePromise<$models.WebhookView>}
 */
export function GetWebhook(project, seq) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.GetWebhook", project, seq).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListCaptures returns the most recent traffic captures, newest-first,
 * optionally filtered to one interception session (0 = all). Bodies and full
 * header maps are omitted (use GetCapture for the detail payload).
 * @param {number} sessionID
 * @returns {$CancellablePromise<$models.CaptureView[]>}
 */
export function ListCaptures(sessionID) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ListCaptures", sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListScripts returns every stored script (all triggers) for the editor
 * sidebar, ordered by trigger then priority.
 * @returns {$CancellablePromise<$models.ScriptView[]>}
 */
export function ListScripts() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ListScripts").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListSessions returns recorded interception sessions, newest-first, for the
 * sidebar's session filter.
 * @returns {$CancellablePromise<$models.SessionView[]>}
 */
export function ListSessions() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ListSessions").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListWebhooks returns the most recent webhooks, newest-first, optionally
 * filtered by project (empty string = all projects). Body/Headers are omitted
 * (use GetWebhook for the full payload).
 * @param {string} project
 * @returns {$CancellablePromise<$models.WebhookView[]>}
 */
export function ListWebhooks(project) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ListWebhooks", project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * RegisterRelay performs `wiretap relay register --save` from the GUI: it
 * registers this PC with the relay's admin API, persists the returned
 * credentials, points the config's tunnel endpoint at the relay, and
 * (re)starts the tunnel.
 * @param {$models.RegisterInput} $in
 * @returns {$CancellablePromise<$models.RegisterView>}
 */
export function RegisterRelay($in) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.RegisterRelay", $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ReplayWebhook re-POSTs a stored webhook to targetURL and returns the upstream
 * HTTP status. Delegates to app.App.ReplayWebhook (byte-exact body + hop-by-hop
 * stripping already handled there).
 * @param {string} project
 * @param {number} seq
 * @param {string} targetURL
 * @returns {$CancellablePromise<$models.ReplayResult>}
 */
export function ReplayWebhook(project, seq, targetURL) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ReplayWebhook", project, seq, targetURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * SaveScript creates (ID == 0) or updates a script and returns its id. The
 * frontend calls this from the editor's Save button.
 * @param {$models.ScriptInput} $in
 * @returns {$CancellablePromise<number>}
 */
export function SaveScript($in) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.SaveScript", $in);
}

/**
 * SaveSettings validates and persists the whole form to config.yaml, then
 * restarts the relay tunnel when its endpoint changed. Interception settings
 * apply to the next `wiretap intercept start`; a store path change takes
 * effect after the app restarts (the open SQLite handle is kept).
 * @param {$models.SettingsInput} $in
 * @returns {$CancellablePromise<$models.SettingsView>}
 */
export function SaveSettings($in) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.SaveSettings", $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetScriptEnabled toggles the enabled flag on one script (sidebar checkbox).
 * @param {number} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetScriptEnabled(id, enabled) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.SetScriptEnabled", id, enabled);
}

/**
 * Status reports build version + app state for the GUI header. It is best-effort
 * about config (a missing config file is not an error here — falls back to
 * defaults, same as the TUI).
 * 
 * ConnectedProjects mirrors app.App.ConnectedProjects — the list the relay
 * says this client owns, set by the tunnel's OnConnect callback. It is nil when
 * no tunnel is attached, so the GUI can render "watching: tunnel down".
 * @returns {$CancellablePromise<$models.StatusView>}
 */
export function Status() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.Status").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * TestScript runs a script body once against a sample exchange and returns the
 * mutated result + logs. It never persists or touches live traffic. A script
 * exception is returned in the view's Error field (not as a Go error) so the
 * editor can render logs alongside the failure.
 * @param {$models.ScriptTestRequest} req
 * @returns {$CancellablePromise<$models.ScriptTestView>}
 */
export function TestScript(req) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.TestScript", req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.TargetView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CaptureView.createFrom;
const $$createType3 = $models.ScriptView.createFrom;
const $$createType4 = $models.SettingsView.createFrom;
const $$createType5 = $models.WebhookView.createFrom;
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = $Create.Array($$createType3);
const $$createType8 = $models.SessionView.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType5);
const $$createType11 = $models.RegisterView.createFrom;
const $$createType12 = $models.ReplayResult.createFrom;
const $$createType13 = $models.StatusView.createFrom;
const $$createType14 = $models.ScriptTestView.createFrom;
