// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bindings is the struct registered with wails.Run as the bound App. Every
 * exported method becomes a callable in the frontend's wailsjs bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteScript removes a script by id.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteScript(id) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.DeleteScript", id);
}

/**
 * GetCapture returns one traffic capture with request/response headers and
 * bodies populated for the detail pane. Returns an error when the row is
 * absent (errors.Is, store.ErrNotFound).
 * @param {number} id
 * @returns {$CancellablePromise<$models.CaptureView>}
 */
export function GetCapture(id) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.GetCapture", id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetScript returns one script by id (the editor loads the full body on
 * selection). Wraps store.ErrNotFound when absent.
 * @param {number} id
 * @returns {$CancellablePromise<$models.ScriptView>}
 */
export function GetScript(id) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.GetScript", id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetWebhook returns one webhook with body + headers populated for the detail
 * view and the replay form. Returns an error suitable for the frontend when the
 * row is absent (errors.Is, store.ErrNotFound).
 * @param {string} project
 * @param {number} seq
 * @returns {$CancellablePromise<$models.WebhookView>}
 */
export function GetWebhook(project, seq) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.GetWebhook", project, seq).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListCaptures returns the most recent traffic captures, newest-first. Bodies
 * and full header maps are omitted (use GetCapture for the detail payload).
 * @returns {$CancellablePromise<$models.CaptureView[]>}
 */
export function ListCaptures() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ListCaptures").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListScripts returns every stored script (all triggers) for the editor
 * sidebar, ordered by trigger then priority.
 * @returns {$CancellablePromise<$models.ScriptView[]>}
 */
export function ListScripts() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ListScripts").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListWebhooks returns the most recent webhooks, newest-first, optionally
 * filtered by project (empty string = all projects). Body/Headers are omitted
 * (use GetWebhook for the full payload).
 * @param {string} project
 * @returns {$CancellablePromise<$models.WebhookView[]>}
 */
export function ListWebhooks(project) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ListWebhooks", project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ReplayWebhook re-POSTs a stored webhook to targetURL and returns the upstream
 * HTTP status. Delegates to app.App.ReplayWebhook (byte-exact body + hop-by-hop
 * stripping already handled there).
 * @param {string} project
 * @param {number} seq
 * @param {string} targetURL
 * @returns {$CancellablePromise<$models.ReplayResult>}
 */
export function ReplayWebhook(project, seq, targetURL) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.ReplayWebhook", project, seq, targetURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * SaveScript creates (ID == 0) or updates a script and returns its id. The
 * frontend calls this from the editor's Save button.
 * @param {$models.ScriptInput} $in
 * @returns {$CancellablePromise<number>}
 */
export function SaveScript($in) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.SaveScript", $in);
}

/**
 * SetScriptEnabled toggles the enabled flag on one script (sidebar checkbox).
 * @param {number} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetScriptEnabled(id, enabled) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.SetScriptEnabled", id, enabled);
}

/**
 * Status reports build version + app state for the GUI header. It is best-effort
 * about config (a missing config file is not an error here — falls back to
 * defaults, same as the TUI).
 * 
 * ConnectedProjects mirrors app.App.ConnectedProjects — the list the relay
 * says this client owns, set by the tunnel's OnConnect callback. It is nil when
 * no tunnel is attached, so the GUI can render "watching: tunnel down".
 * @returns {$CancellablePromise<$models.StatusView>}
 */
export function Status() {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.Status").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * TestScript runs a script body once against a sample exchange and returns the
 * mutated result + logs. It never persists or touches live traffic. A script
 * exception is returned in the view's Error field (not as a Go error) so the
 * editor can render logs alongside the failure.
 * @param {$models.ScriptTestRequest} req
 * @returns {$CancellablePromise<$models.ScriptTestView>}
 */
export function TestScript(req) {
    return $Call.ByName("github.com/plutack/wiretap/internal/gui.Bindings.TestScript", req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CaptureView.createFrom;
const $$createType1 = $models.ScriptView.createFrom;
const $$createType2 = $models.WebhookView.createFrom;
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = $Create.Array($$createType2);
const $$createType6 = $models.ReplayResult.createFrom;
const $$createType7 = $models.StatusView.createFrom;
const $$createType8 = $models.ScriptTestView.createFrom;
