// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * CaptureView is the GUI DTO for a traffic capture. Bodies are omitted in list
 * responses; GetCapture fills them for the detail pane.
 */
export class CaptureView {
    /**
     * Creates a new CaptureView instance.
     * @param {Partial<CaptureView>} [$$source = {}] - The source object to create the CaptureView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["session_id"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * RFC3339 UTC
             * @member
             * @type {string}
             */
            this["at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] } | undefined}
             */
            this["req_headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["req_body"] = undefined;
        }
        if (!("req_body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["req_body_len"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] } | undefined}
             */
            this["resp_headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resp_body"] = undefined;
        }
        if (!("resp_body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resp_body_len"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureView}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("req_headers" in $$parsedSource) {
            $$parsedSource["req_headers"] = $$createField6_0($$parsedSource["req_headers"]);
        }
        if ("resp_headers" in $$parsedSource) {
            $$parsedSource["resp_headers"] = $$createField9_0($$parsedSource["resp_headers"]);
        }
        return new CaptureView(/** @type {Partial<CaptureView>} */($$parsedSource));
    }
}

/**
 * ClientView is one concrete library/tool within a TargetView.
 */
export class ClientView {
    /**
     * Creates a new ClientView instance.
     * @param {Partial<ClientView>} [$$source = {}] - The source object to create the ClientView.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClientView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientView(/** @type {Partial<ClientView>} */($$parsedSource));
    }
}

/**
 * RegisterInput is the relay registration form: the relay URL (HTTPS base or
 * wss tunnel form — both accepted), the admin token (used once, not stored),
 * the project paths to claim, and an optional display name.
 */
export class RegisterInput {
    /**
     * Creates a new RegisterInput instance.
     * @param {Partial<RegisterInput>} [$$source = {}] - The source object to create the RegisterInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["projects"] = [];
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegisterInput}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField2_0($$parsedSource["projects"]);
        }
        return new RegisterInput(/** @type {Partial<RegisterInput>} */($$parsedSource));
    }
}

/**
 * RegisterView reports a successful registration: the assigned client id,
 * the claimed projects, and the tunnel URL written to the config.
 */
export class RegisterView {
    /**
     * Creates a new RegisterView instance.
     * @param {Partial<RegisterView>} [$$source = {}] - The source object to create the RegisterView.
     */
    constructor($$source = {}) {
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["projects"] = [];
        }
        if (!("tunnel_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegisterView}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        return new RegisterView(/** @type {Partial<RegisterView>} */($$parsedSource));
    }
}

/**
 * ReplayResult is the return value of ReplayWebhook: the upstream HTTP status.
 */
export class ReplayResult {
    /**
     * Creates a new ReplayResult instance.
     * @param {Partial<ReplayResult>} [$$source = {}] - The source object to create the ReplayResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplayResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReplayResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplayResult(/** @type {Partial<ReplayResult>} */($$parsedSource));
    }
}

/**
 * ScriptInput is the payload the editor sends to SaveScript. ID == 0 means
 * "create"; a non-zero ID updates that row.
 */
export class ScriptInput {
    /**
     * Creates a new ScriptInput instance.
     * @param {Partial<ScriptInput>} [$$source = {}] - The source object to create the ScriptInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("trigger" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trigger"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptInput(/** @type {Partial<ScriptInput>} */($$parsedSource));
    }
}

/**
 * ScriptTestRequest is the test-run payload: the script body plus a sample
 * exchange (usually filled from the selected capture/webhook).
 */
export class ScriptTestRequest {
    /**
     * Creates a new ScriptTestRequest instance.
     * @param {Partial<ScriptTestRequest>} [$$source = {}] - The source object to create the ScriptTestRequest.
     */
    constructor($$source = {}) {
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("req_body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["req_body"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptTestRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptTestRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new ScriptTestRequest(/** @type {Partial<ScriptTestRequest>} */($$parsedSource));
    }
}

/**
 * ScriptTestView is the test-run outcome the editor renders: the mutated
 * request/response plus console logs and rejection state. Error, when set, is
 * the script exception message (logs are still populated up to the failure).
 */
export class ScriptTestView {
    /**
     * Creates a new ScriptTestView instance.
     * @param {Partial<ScriptTestView>} [$$source = {}] - The source object to create the ScriptTestView.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("req_headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["req_headers"] = {};
        }
        if (!("req_body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["req_body"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("resp_headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["resp_headers"] = {};
        }
        if (!("resp_body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resp_body"] = "";
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (!("rejected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rejected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reject_reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptTestView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptTestView}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("req_headers" in $$parsedSource) {
            $$parsedSource["req_headers"] = $$createField2_0($$parsedSource["req_headers"]);
        }
        if ("resp_headers" in $$parsedSource) {
            $$parsedSource["resp_headers"] = $$createField5_0($$parsedSource["resp_headers"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField7_0($$parsedSource["logs"]);
        }
        return new ScriptTestView(/** @type {Partial<ScriptTestView>} */($$parsedSource));
    }
}

/**
 * ScriptView is the GUI + wailsjs DTO for a stored script. It mirrors
 * store.ScriptRow with JSON-friendly field names; timestamps are RFC3339 UTC.
 */
export class ScriptView {
    /**
     * Creates a new ScriptView instance.
     * @param {Partial<ScriptView>} [$$source = {}] - The source object to create the ScriptView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("trigger" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trigger"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptView(/** @type {Partial<ScriptView>} */($$parsedSource));
    }
}

/**
 * SessionView is the GUI DTO for one interception session (a `wiretap
 * intercept start` run). EndedAt is empty while the session is running — or
 * when it crashed without cleanup.
 */
export class SessionView {
    /**
     * Creates a new SessionView instance.
     * @param {Partial<SessionView>} [$$source = {}] - The source object to create the SessionView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("started_at" in $$source)) {
            /**
             * RFC3339 UTC
             * @member
             * @type {string}
             */
            this["started_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * empty = running/crashed
             * @member
             * @type {string | undefined}
             */
            this["ended_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shell"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxy_addr"] = undefined;
        }
        if (!("captures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["captures"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionView(/** @type {Partial<SessionView>} */($$parsedSource));
    }
}

/**
 * SettingsInput is the editable subset SaveSettings writes back. Empty
 * strings are meaningful ("use the default"), so the whole form is sent
 * every time rather than a patch.
 */
export class SettingsInput {
    /**
     * Creates a new SettingsInput instance.
     * @param {Partial<SettingsInput>} [$$source = {}] - The source object to create the SettingsInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("forward_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["forward_url"] = "";
        }
        if (!("store_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_path"] = "";
        }
        if (!("tui_theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tui_theme"] = "";
        }
        if (!("proxy_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxy_addr"] = "";
        }
        if (!("local_api_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_api_addr"] = "";
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shell"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInput(/** @type {Partial<SettingsInput>} */($$parsedSource));
    }
}

/**
 * SettingsView is the full settings payload: current config values, resolved
 * paths for display, and the relay registration state (credentials minus the
 * secret token).
 */
export class SettingsView {
    /**
     * Creates a new SettingsView instance.
     * @param {Partial<SettingsView>} [$$source = {}] - The source object to create the SettingsView.
     */
    constructor($$source = {}) {
        if (!("config_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config_path"] = "";
        }
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("forward_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["forward_url"] = "";
        }
        if (!("store_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_path"] = "";
        }
        if (!("store_default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_default"] = "";
        }
        if (!("tui_theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tui_theme"] = "";
        }
        if (!("proxy_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxy_addr"] = "";
        }
        if (!("local_api_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_api_addr"] = "";
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shell"] = "";
        }
        if (!("registered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["registered"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["client_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["projects"] = undefined;
        }
        if (!("creds_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["creds_path"] = "";
        }
        if (!("tunnel_running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tunnel_running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsView}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField11_0($$parsedSource["projects"]);
        }
        return new SettingsView(/** @type {Partial<SettingsView>} */($$parsedSource));
    }
}

/**
 * StatusView is the status-bar payload: build version plus the resolved app
 * state the GUI shows in its header.
 */
export class StatusView {
    /**
     * Creates a new StatusView instance.
     * @param {Partial<StatusView>} [$$source = {}] - The source object to create the StatusView.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("store_open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["store_open"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["relay_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["forward_url"] = undefined;
        }
        if (!("tunnel_running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tunnel_running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["connected_projects"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connected_projects" in $$parsedSource) {
            $$parsedSource["connected_projects"] = $$createField5_0($$parsedSource["connected_projects"]);
        }
        return new StatusView(/** @type {Partial<StatusView>} */($$parsedSource));
    }
}

/**
 * TargetView is one snippet language in the export dropdown, with its
 * available clients. Mirrors export.Target.
 */
export class TargetView {
    /**
     * Creates a new TargetView instance.
     * @param {Partial<TargetView>} [$$source = {}] - The source object to create the TargetView.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("clients" in $$source)) {
            /**
             * @member
             * @type {ClientView[]}
             */
            this["clients"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TargetView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clients" in $$parsedSource) {
            $$parsedSource["clients"] = $$createField3_0($$parsedSource["clients"]);
        }
        return new TargetView(/** @type {Partial<TargetView>} */($$parsedSource));
    }
}

/**
 * WebhookView is the GUI + wailsjs DTO for a webhook row. Body is omitted in
 * list responses (BodyLen set); GetWebhook fills Body + Headers for the detail
 * view and the replay form.
 */
export class WebhookView {
    /**
     * Creates a new WebhookView instance.
     * @param {Partial<WebhookView>} [$$source = {}] - The source object to create the WebhookView.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("received_at" in $$source)) {
            /**
             * RFC3339 UTC
             * @member
             * @type {string}
             */
            this["received_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] } | undefined}
             */
            this["headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["body"] = undefined;
        }
        if (!("body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["body_len"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebhookView}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        return new WebhookView(/** @type {Partial<WebhookView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = ClientView.createFrom;
const $$createType4 = $Create.Array($$createType3);
