// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * CaptureBodyView is one bounded or complete body fetched on demand.
 */
export class CaptureBodyView {
    /**
     * Creates a new CaptureBodyView instance.
     * @param {Partial<CaptureBodyView>} [$$source = {}] - The source object to create the CaptureBodyView.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["body_base64"] = undefined;
        }
        if (!("body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["body_len"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["truncated"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureBodyView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureBodyView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureBodyView(/** @type {Partial<CaptureBodyView>} */($$parsedSource));
    }
}

/**
 * CapturePageView is one page of capture rows plus the size of the whole
 * filtered set, so the deck can show "100 of 1,432 matches".
 */
export class CapturePageView {
    /**
     * Creates a new CapturePageView instance.
     * @param {Partial<CapturePageView>} [$$source = {}] - The source object to create the CapturePageView.
     */
    constructor($$source = {}) {
        if (!("captures" in $$source)) {
            /**
             * @member
             * @type {CaptureView[]}
             */
            this["captures"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapturePageView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CapturePageView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("captures" in $$parsedSource) {
            $$parsedSource["captures"] = $$createField0_0($$parsedSource["captures"]);
        }
        return new CapturePageView(/** @type {Partial<CapturePageView>} */($$parsedSource));
    }
}

/**
 * CaptureQueryInput is the GUI's capture list request. The zero value lists the
 * newest page with no filtering, which is what the dashboard shows by default.
 * 
 * The filter travels to SQLite rather than being applied in the frontend,
 * because the frontend only ever holds one page: matching there could never find
 * a capture older than that page.
 */
export class CaptureQueryInput {
    /**
     * Creates a new CaptureQueryInput instance.
     * @param {Partial<CaptureQueryInput>} [$$source = {}] - The source object to create the CaptureQueryInput.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session_id"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["query"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Body extends Query matching to request/response bodies. Opt-in: no index
             * can serve a substring match, so it reads every body it scans.
             * @member
             * @type {boolean | undefined}
             */
            this["body"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * BeforeID pages backwards from a previous page's last row.
             * @member
             * @type {number | undefined}
             */
            this["before_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Limit caps the page; 0 uses the GUI list cap.
             * @member
             * @type {number | undefined}
             */
            this["limit"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureQueryInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureQueryInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureQueryInput(/** @type {Partial<CaptureQueryInput>} */($$parsedSource));
    }
}

/**
 * CaptureView is the GUI DTO for a traffic capture. Bodies are omitted in list
 * responses; GetCapture fills bounded Base64 previews for the detail pane.
 */
export class CaptureView {
    /**
     * Creates a new CaptureView instance.
     * @param {Partial<CaptureView>} [$$source = {}] - The source object to create the CaptureView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["session_id"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * RFC3339 UTC
             * @member
             * @type {string}
             */
            this["at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] } | undefined}
             */
            this["req_headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["req_body_base64"] = undefined;
        }
        if (!("req_body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["req_body_len"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["req_body_truncated"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] } | undefined}
             */
            this["resp_headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resp_body_base64"] = undefined;
        }
        if (!("resp_body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resp_body_len"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["resp_body_truncated"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureView}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        const $$createField10_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("req_headers" in $$parsedSource) {
            $$parsedSource["req_headers"] = $$createField6_0($$parsedSource["req_headers"]);
        }
        if ("resp_headers" in $$parsedSource) {
            $$parsedSource["resp_headers"] = $$createField10_0($$parsedSource["resp_headers"]);
        }
        return new CaptureView(/** @type {Partial<CaptureView>} */($$parsedSource));
    }
}

/**
 * ClientView is one concrete library/tool within a TargetView.
 */
export class ClientView {
    /**
     * Creates a new ClientView instance.
     * @param {Partial<ClientView>} [$$source = {}] - The source object to create the ClientView.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClientView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientView(/** @type {Partial<ClientView>} */($$parsedSource));
    }
}

/**
 * ComposeRecipeDraftView is the editable request produced by a recipe. Recipe
 * application never sends it and deliberately disables the automatic replay
 * chain until the user opts back in.
 */
export class ComposeRecipeDraftView {
    /**
     * Creates a new ComposeRecipeDraftView instance.
     * @param {Partial<ComposeRecipeDraftView>} [$$source = {}] - The source object to create the ComposeRecipeDraftView.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("apply_transforms" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["apply_transforms"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["logs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComposeRecipeDraftView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComposeRecipeDraftView}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField5_0($$parsedSource["logs"]);
        }
        return new ComposeRecipeDraftView(/** @type {Partial<ComposeRecipeDraftView>} */($$parsedSource));
    }
}

/**
 * ComposeRecipeInput is raw source text plus the base destination supplied to
 * a selected preparation recipe.
 */
export class ComposeRecipeInput {
    /**
     * Creates a new ComposeRecipeInput instance.
     * @param {Partial<ComposeRecipeInput>} [$$source = {}] - The source object to create the ComposeRecipeInput.
     */
    constructor($$source = {}) {
        if (!("recipe_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["recipe_id"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComposeRecipeInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComposeRecipeInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComposeRecipeInput(/** @type {Partial<ComposeRecipeInput>} */($$parsedSource));
    }
}

/**
 * ComposeRecipeView describes an enabled, user-authored source-to-request
 * adapter available in the composer.
 */
export class ComposeRecipeView {
    /**
     * Creates a new ComposeRecipeView instance.
     * @param {Partial<ComposeRecipeView>} [$$source = {}] - The source object to create the ComposeRecipeView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComposeRecipeView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComposeRecipeView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComposeRecipeView(/** @type {Partial<ComposeRecipeView>} */($$parsedSource));
    }
}

/**
 * ComposeRequestInput is an arbitrary request authored in the GUI.
 */
export class ComposeRequestInput {
    /**
     * Creates a new ComposeRequestInput instance.
     * @param {Partial<ComposeRequestInput>} [$$source = {}] - The source object to create the ComposeRequestInput.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("apply_transforms" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["apply_transforms"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComposeRequestInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComposeRequestInput}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new ComposeRequestInput(/** @type {Partial<ComposeRequestInput>} */($$parsedSource));
    }
}

/**
 * ComposeResponseView is the bounded response shown by the composer.
 */
export class ComposeResponseView {
    /**
     * Creates a new ComposeResponseView instance.
     * @param {Partial<ComposeResponseView>} [$$source = {}] - The source object to create the ComposeResponseView.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["headers"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["body_base64"] = undefined;
        }
        if (!("body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["body_len"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["truncated"] = undefined;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComposeResponseView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComposeResponseView}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField1_0($$parsedSource["headers"]);
        }
        return new ComposeResponseView(/** @type {Partial<ComposeResponseView>} */($$parsedSource));
    }
}

/**
 * RegisterInput is the relay registration form: the relay URL (HTTPS base or
 * wss tunnel form — both accepted), the admin token (used once, not stored),
 * the project paths to claim, and an optional display name.
 */
export class RegisterInput {
    /**
     * Creates a new RegisterInput instance.
     * @param {Partial<RegisterInput>} [$$source = {}] - The source object to create the RegisterInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["projects"] = [];
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegisterInput}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField2_0($$parsedSource["projects"]);
        }
        return new RegisterInput(/** @type {Partial<RegisterInput>} */($$parsedSource));
    }
}

/**
 * RegisterView reports a successful registration: the assigned client id,
 * initial project subscriptions, and the tunnel URL written to the config.
 */
export class RegisterView {
    /**
     * Creates a new RegisterView instance.
     * @param {Partial<RegisterView>} [$$source = {}] - The source object to create the RegisterView.
     */
    constructor($$source = {}) {
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["projects"] = [];
        }
        if (!("tunnel_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegisterView}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        return new RegisterView(/** @type {Partial<RegisterView>} */($$parsedSource));
    }
}

/**
 * RelayAdminAddProjectInput assigns a new project path to an existing client.
 */
export class RelayAdminAddProjectInput {
    /**
     * Creates a new RelayAdminAddProjectInput instance.
     * @param {Partial<RelayAdminAddProjectInput>} [$$source = {}] - The source object to create the RelayAdminAddProjectInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminAddProjectInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminAddProjectInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminAddProjectInput(/** @type {Partial<RelayAdminAddProjectInput>} */($$parsedSource));
    }
}

export class RelayAdminClientView {
    /**
     * Creates a new RelayAdminClientView instance.
     * @param {Partial<RelayAdminClientView>} [$$source = {}] - The source object to create the RelayAdminClientView.
     */
    constructor($$source = {}) {
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["display_name"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_seen_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["projects"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminClientView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminClientView}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField4_0($$parsedSource["projects"]);
        }
        return new RelayAdminClientView(/** @type {Partial<RelayAdminClientView>} */($$parsedSource));
    }
}

/**
 * RelayAdminCreateClientInput creates credentials for another relay client.
 * Unlike RegisterRelay, it does not replace this desktop's saved identity.
 */
export class RelayAdminCreateClientInput {
    /**
     * Creates a new RelayAdminCreateClientInput instance.
     * @param {Partial<RelayAdminCreateClientInput>} [$$source = {}] - The source object to create the RelayAdminCreateClientInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminCreateClientInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminCreateClientInput}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField3_0($$parsedSource["projects"]);
        }
        return new RelayAdminCreateClientInput(/** @type {Partial<RelayAdminCreateClientInput>} */($$parsedSource));
    }
}

/**
 * RelayAdminCredentialsView contains a newly-created client token. The relay
 * returns it once, so the GUI keeps it only in component memory for copying or
 * downloading as a portable handoff.
 */
export class RelayAdminCredentialsView {
    /**
     * Creates a new RelayAdminCredentialsView instance.
     * @param {Partial<RelayAdminCredentialsView>} [$$source = {}] - The source object to create the RelayAdminCredentialsView.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("client_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_token"] = "";
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminCredentialsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminCredentialsView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField5_0($$parsedSource["projects"]);
        }
        return new RelayAdminCredentialsView(/** @type {Partial<RelayAdminCredentialsView>} */($$parsedSource));
    }
}

/**
 * RelayAdminDeleteClientInput revokes an identity and its subscriptions.
 */
export class RelayAdminDeleteClientInput {
    /**
     * Creates a new RelayAdminDeleteClientInput instance.
     * @param {Partial<RelayAdminDeleteClientInput>} [$$source = {}] - The source object to create the RelayAdminDeleteClientInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminDeleteClientInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminDeleteClientInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminDeleteClientInput(/** @type {Partial<RelayAdminDeleteClientInput>} */($$parsedSource));
    }
}

/**
 * RelayAdminDeleteProjectInput permanently removes a project binding and its
 * queued relay-side webhook history.
 */
export class RelayAdminDeleteProjectInput {
    /**
     * Creates a new RelayAdminDeleteProjectInput instance.
     * @param {Partial<RelayAdminDeleteProjectInput>} [$$source = {}] - The source object to create the RelayAdminDeleteProjectInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminDeleteProjectInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminDeleteProjectInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminDeleteProjectInput(/** @type {Partial<RelayAdminDeleteProjectInput>} */($$parsedSource));
    }
}

export class RelayAdminDeleteWebhooksInput {
    /**
     * Creates a new RelayAdminDeleteWebhooksInput instance.
     * @param {Partial<RelayAdminDeleteWebhooksInput>} [$$source = {}] - The source object to create the RelayAdminDeleteWebhooksInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("seqs" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["seqs"] = [];
        }
        if (!("through_seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["through_seq"] = 0;
        }
        if (!("all" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["all"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminDeleteWebhooksInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminDeleteWebhooksInput}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("seqs" in $$parsedSource) {
            $$parsedSource["seqs"] = $$createField3_0($$parsedSource["seqs"]);
        }
        return new RelayAdminDeleteWebhooksInput(/** @type {Partial<RelayAdminDeleteWebhooksInput>} */($$parsedSource));
    }
}

/**
 * RelayAdminInput carries the ephemeral credentials for one relay admin
 * operation. The admin token crosses the Wails bridge for the request only;
 * wiretap never writes it to config or credentials storage.
 */
export class RelayAdminInput {
    /**
     * Creates a new RelayAdminInput instance.
     * @param {Partial<RelayAdminInput>} [$$source = {}] - The source object to create the RelayAdminInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminInput(/** @type {Partial<RelayAdminInput>} */($$parsedSource));
    }
}

export class RelayAdminListWebhooksInput {
    /**
     * Creates a new RelayAdminListWebhooksInput instance.
     * @param {Partial<RelayAdminListWebhooksInput>} [$$source = {}] - The source object to create the RelayAdminListWebhooksInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("after_seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["after_seq"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminListWebhooksInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminListWebhooksInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminListWebhooksInput(/** @type {Partial<RelayAdminListWebhooksInput>} */($$parsedSource));
    }
}

/**
 * RelayAdminOverviewView is the bounded server-management snapshot rendered
 * by Settings. It deliberately contains no client or admin secret.
 */
export class RelayAdminOverviewView {
    /**
     * Creates a new RelayAdminOverviewView instance.
     * @param {Partial<RelayAdminOverviewView>} [$$source = {}] - The source object to create the RelayAdminOverviewView.
     */
    constructor($$source = {}) {
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("tunnel_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tunnel_count"] = 0;
        }
        if (!("clients" in $$source)) {
            /**
             * @member
             * @type {RelayAdminClientView[]}
             */
            this["clients"] = [];
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {RelayAdminProjectView[]}
             */
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminOverviewView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminOverviewView}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clients" in $$parsedSource) {
            $$parsedSource["clients"] = $$createField4_0($$parsedSource["clients"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField5_0($$parsedSource["projects"]);
        }
        return new RelayAdminOverviewView(/** @type {Partial<RelayAdminOverviewView>} */($$parsedSource));
    }
}

export class RelayAdminProfileView {
    /**
     * Creates a new RelayAdminProfileView instance.
     * @param {Partial<RelayAdminProfileView>} [$$source = {}] - The source object to create the RelayAdminProfileView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("last_used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_used"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminProfileView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminProfileView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminProfileView(/** @type {Partial<RelayAdminProfileView>} */($$parsedSource));
    }
}

export class RelayAdminProjectView {
    /**
     * Creates a new RelayAdminProjectView instance.
     * @param {Partial<RelayAdminProjectView>} [$$source = {}] - The source object to create the RelayAdminProjectView.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("next_seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["next_seq"] = 0;
        }
        if (!("webhook_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["webhook_count"] = 0;
        }
        if (!("subscriptions" in $$source)) {
            /**
             * @member
             * @type {RelayAdminSubscriptionView[]}
             */
            this["subscriptions"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["client_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["acked_seq"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminProjectView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminProjectView}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscriptions" in $$parsedSource) {
            $$parsedSource["subscriptions"] = $$createField4_0($$parsedSource["subscriptions"]);
        }
        return new RelayAdminProjectView(/** @type {Partial<RelayAdminProjectView>} */($$parsedSource));
    }
}

/**
 * RelayAdminReassignProjectInput moves a path to another registered client.
 */
export class RelayAdminReassignProjectInput {
    /**
     * Creates a new RelayAdminReassignProjectInput instance.
     * @param {Partial<RelayAdminReassignProjectInput>} [$$source = {}] - The source object to create the RelayAdminReassignProjectInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("new_client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["new_client_id"] = "";
        }
        if (!("force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminReassignProjectInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminReassignProjectInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminReassignProjectInput(/** @type {Partial<RelayAdminReassignProjectInput>} */($$parsedSource));
    }
}

export class RelayAdminSaveProfileInput {
    /**
     * Creates a new RelayAdminSaveProfileInput instance.
     * @param {Partial<RelayAdminSaveProfileInput>} [$$source = {}] - The source object to create the RelayAdminSaveProfileInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminSaveProfileInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminSaveProfileInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminSaveProfileInput(/** @type {Partial<RelayAdminSaveProfileInput>} */($$parsedSource));
    }
}

export class RelayAdminSubscriptionInput {
    /**
     * Creates a new RelayAdminSubscriptionInput instance.
     * @param {Partial<RelayAdminSubscriptionInput>} [$$source = {}] - The source object to create the RelayAdminSubscriptionInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("admin_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_token"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("include_history" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["include_history"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminSubscriptionInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminSubscriptionInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminSubscriptionInput(/** @type {Partial<RelayAdminSubscriptionInput>} */($$parsedSource));
    }
}

export class RelayAdminSubscriptionView {
    /**
     * Creates a new RelayAdminSubscriptionView instance.
     * @param {Partial<RelayAdminSubscriptionView>} [$$source = {}] - The source object to create the RelayAdminSubscriptionView.
     */
    constructor($$source = {}) {
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("start_seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start_seq"] = 0;
        }
        if (!("acked_seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["acked_seq"] = 0;
        }
        if (!("pending" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminSubscriptionView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminSubscriptionView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminSubscriptionView(/** @type {Partial<RelayAdminSubscriptionView>} */($$parsedSource));
    }
}

export class RelayAdminWebhookPageView {
    /**
     * Creates a new RelayAdminWebhookPageView instance.
     * @param {Partial<RelayAdminWebhookPageView>} [$$source = {}] - The source object to create the RelayAdminWebhookPageView.
     */
    constructor($$source = {}) {
        if (!("webhooks" in $$source)) {
            /**
             * @member
             * @type {RelayAdminWebhookView[]}
             */
            this["webhooks"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["next_after_seq"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminWebhookPageView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminWebhookPageView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("webhooks" in $$parsedSource) {
            $$parsedSource["webhooks"] = $$createField0_0($$parsedSource["webhooks"]);
        }
        return new RelayAdminWebhookPageView(/** @type {Partial<RelayAdminWebhookPageView>} */($$parsedSource));
    }
}

export class RelayAdminWebhookView {
    /**
     * Creates a new RelayAdminWebhookView instance.
     * @param {Partial<RelayAdminWebhookView>} [$$source = {}] - The source object to create the RelayAdminWebhookView.
     */
    constructor($$source = {}) {
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("received_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["received_at"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source_ip"] = undefined;
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("body_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["body_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayAdminWebhookView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelayAdminWebhookView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayAdminWebhookView(/** @type {Partial<RelayAdminWebhookView>} */($$parsedSource));
    }
}

/**
 * ReplayResult is the return value of ReplayWebhook: the upstream HTTP status.
 */
export class ReplayResult {
    /**
     * Creates a new ReplayResult instance.
     * @param {Partial<ReplayResult>} [$$source = {}] - The source object to create the ReplayResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplayResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReplayResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplayResult(/** @type {Partial<ReplayResult>} */($$parsedSource));
    }
}

/**
 * ScriptInput is the payload the editor sends to SaveScript. ID == 0 means
 * "create"; a non-zero ID updates that row.
 */
export class ScriptInput {
    /**
     * Creates a new ScriptInput instance.
     * @param {Partial<ScriptInput>} [$$source = {}] - The source object to create the ScriptInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("trigger" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trigger"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptInput(/** @type {Partial<ScriptInput>} */($$parsedSource));
    }
}

/**
 * ScriptTestRequest is the test-run payload: the script body plus a sample
 * exchange (usually filled from the selected capture/webhook).
 */
export class ScriptTestRequest {
    /**
     * Creates a new ScriptTestRequest instance.
     * @param {Partial<ScriptTestRequest>} [$$source = {}] - The source object to create the ScriptTestRequest.
     */
    constructor($$source = {}) {
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("req_body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["req_body"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptTestRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptTestRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new ScriptTestRequest(/** @type {Partial<ScriptTestRequest>} */($$parsedSource));
    }
}

/**
 * ScriptTestView is the test-run outcome the editor renders: the mutated
 * request/response plus console logs and rejection state. Error, when set, is
 * the script exception message (logs are still populated up to the failure).
 */
export class ScriptTestView {
    /**
     * Creates a new ScriptTestView instance.
     * @param {Partial<ScriptTestView>} [$$source = {}] - The source object to create the ScriptTestView.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("req_headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["req_headers"] = {};
        }
        if (!("req_body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["req_body"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("resp_headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["resp_headers"] = {};
        }
        if (!("resp_body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resp_body"] = "";
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (!("rejected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rejected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reject_reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptTestView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptTestView}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("req_headers" in $$parsedSource) {
            $$parsedSource["req_headers"] = $$createField2_0($$parsedSource["req_headers"]);
        }
        if ("resp_headers" in $$parsedSource) {
            $$parsedSource["resp_headers"] = $$createField5_0($$parsedSource["resp_headers"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField7_0($$parsedSource["logs"]);
        }
        return new ScriptTestView(/** @type {Partial<ScriptTestView>} */($$parsedSource));
    }
}

/**
 * ScriptView is the GUI + wailsjs DTO for a stored script. It mirrors
 * store.ScriptRow with JSON-friendly field names; timestamps are RFC3339 UTC.
 */
export class ScriptView {
    /**
     * Creates a new ScriptView instance.
     * @param {Partial<ScriptView>} [$$source = {}] - The source object to create the ScriptView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("trigger" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trigger"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptView(/** @type {Partial<ScriptView>} */($$parsedSource));
    }
}

export class SessionPageView {
    /**
     * Creates a new SessionPageView instance.
     * @param {Partial<SessionPageView>} [$$source = {}] - The source object to create the SessionPageView.
     */
    constructor($$source = {}) {
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {SessionView[]}
             */
            this["sessions"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionPageView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionPageView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField0_0($$parsedSource["sessions"]);
        }
        return new SessionPageView(/** @type {Partial<SessionPageView>} */($$parsedSource));
    }
}

/**
 * SessionView is the GUI DTO for one interception session (a `wiretap
 * intercept start` run). EndedAt is empty only while the session is still
 * running; Interrupted marks a session that ended without a clean shutdown,
 * which startup closes out with a backfilled EndedAt.
 */
export class SessionView {
    /**
     * Creates a new SessionView instance.
     * @param {Partial<SessionView>} [$$source = {}] - The source object to create the SessionView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("started_at" in $$source)) {
            /**
             * RFC3339 UTC
             * @member
             * @type {string}
             */
            this["started_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * empty = still running
             * @member
             * @type {string | undefined}
             */
            this["ended_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shell"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxy_addr"] = undefined;
        }
        if (!("captures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["captures"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("interrupted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["interrupted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionView(/** @type {Partial<SessionView>} */($$parsedSource));
    }
}

/**
 * SettingsInput is the editable subset SaveSettings writes back. Empty
 * strings are meaningful ("use the default"), so the whole form is sent
 * every time rather than a patch.
 */
export class SettingsInput {
    /**
     * Creates a new SettingsInput instance.
     * @param {Partial<SettingsInput>} [$$source = {}] - The source object to create the SettingsInput.
     */
    constructor($$source = {}) {
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("forward_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["forward_url"] = "";
        }
        if (!("store_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_path"] = "";
        }
        if (!("tui_theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tui_theme"] = "";
        }
        if (!("native_titlebar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["native_titlebar"] = "";
        }
        if (!("proxy_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxy_addr"] = "";
        }
        if (!("local_api_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_api_addr"] = "";
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shell"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInput(/** @type {Partial<SettingsInput>} */($$parsedSource));
    }
}

/**
 * SettingsView is the full settings payload: current config values, resolved
 * paths for display, and the relay registration state (credentials minus the
 * secret token).
 */
export class SettingsView {
    /**
     * Creates a new SettingsView instance.
     * @param {Partial<SettingsView>} [$$source = {}] - The source object to create the SettingsView.
     */
    constructor($$source = {}) {
        if (!("config_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config_path"] = "";
        }
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("forward_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["forward_url"] = "";
        }
        if (!("store_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_path"] = "";
        }
        if (!("store_default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_default"] = "";
        }
        if (!("tui_theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tui_theme"] = "";
        }
        if (!("native_titlebar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["native_titlebar"] = "";
        }
        if (!("proxy_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxy_addr"] = "";
        }
        if (!("local_api_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_api_addr"] = "";
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shell"] = "";
        }
        if (!("registered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["registered"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["client_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["projects"] = undefined;
        }
        if (!("creds_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["creds_path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["token_storage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["token_warning"] = undefined;
        }
        if (!("tunnel_running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tunnel_running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsView}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField12_0($$parsedSource["projects"]);
        }
        return new SettingsView(/** @type {Partial<SettingsView>} */($$parsedSource));
    }
}

/**
 * StatusView is the status-bar payload: build version plus the resolved app
 * state the GUI shows in its header.
 */
export class StatusView {
    /**
     * Creates a new StatusView instance.
     * @param {Partial<StatusView>} [$$source = {}] - The source object to create the StatusView.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("store_open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["store_open"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["relay_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["forward_url"] = undefined;
        }
        if (!("tunnel_running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tunnel_running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["connected_projects"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connected_projects" in $$parsedSource) {
            $$parsedSource["connected_projects"] = $$createField5_0($$parsedSource["connected_projects"]);
        }
        return new StatusView(/** @type {Partial<StatusView>} */($$parsedSource));
    }
}

/**
 * TargetView is one snippet language in the export dropdown, with its
 * available clients. Mirrors export.Target.
 */
export class TargetView {
    /**
     * Creates a new TargetView instance.
     * @param {Partial<TargetView>} [$$source = {}] - The source object to create the TargetView.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("clients" in $$source)) {
            /**
             * @member
             * @type {ClientView[]}
             */
            this["clients"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TargetView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clients" in $$parsedSource) {
            $$parsedSource["clients"] = $$createField3_0($$parsedSource["clients"]);
        }
        return new TargetView(/** @type {Partial<TargetView>} */($$parsedSource));
    }
}

/**
 * TransformFileView is an imported portable transform. ID is intentionally
 * absent: the GUI opens this as an unsaved draft for review and testing.
 */
export class TransformFileView {
    /**
     * Creates a new TransformFileView instance.
     * @param {Partial<TransformFileView>} [$$source = {}] - The source object to create the TransformFileView.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("trigger" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trigger"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransformFileView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TransformFileView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransformFileView(/** @type {Partial<TransformFileView>} */($$parsedSource));
    }
}

/**
 * WebhookPageView is one page of webhook summaries plus the filtered-set size.
 */
export class WebhookPageView {
    /**
     * Creates a new WebhookPageView instance.
     * @param {Partial<WebhookPageView>} [$$source = {}] - The source object to create the WebhookPageView.
     */
    constructor($$source = {}) {
        if (!("webhooks" in $$source)) {
            /**
             * @member
             * @type {WebhookView[]}
             */
            this["webhooks"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookPageView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebhookPageView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("webhooks" in $$parsedSource) {
            $$parsedSource["webhooks"] = $$createField0_0($$parsedSource["webhooks"]);
        }
        return new WebhookPageView(/** @type {Partial<WebhookPageView>} */($$parsedSource));
    }
}

/**
 * WebhookQueryInput is the GUI's webhook list request; the counterpart of
 * CaptureQueryInput.
 */
export class WebhookQueryInput {
    /**
     * Creates a new WebhookQueryInput instance.
     * @param {Partial<WebhookQueryInput>} [$$source = {}] - The source object to create the WebhookQueryInput.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["project"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["query"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["before_seq"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["limit"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookQueryInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebhookQueryInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebhookQueryInput(/** @type {Partial<WebhookQueryInput>} */($$parsedSource));
    }
}

/**
 * WebhookView is the GUI + wailsjs DTO for a webhook row. Body is omitted in
 * list responses (BodyLen set); GetWebhook fills Body + Headers for the detail
 * view and the replay form.
 */
export class WebhookView {
    /**
     * Creates a new WebhookView instance.
     * @param {Partial<WebhookView>} [$$source = {}] - The source object to create the WebhookView.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("received_at" in $$source)) {
            /**
             * RFC3339 UTC
             * @member
             * @type {string}
             */
            this["received_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] } | undefined}
             */
            this["headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["body"] = undefined;
        }
        if (!("body_len" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["body_len"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebhookView}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        return new WebhookView(/** @type {Partial<WebhookView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CaptureView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = RelayAdminClientView.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = RelayAdminProjectView.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = RelayAdminSubscriptionView.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = RelayAdminWebhookView.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = SessionView.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ClientView.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = WebhookView.createFrom;
const $$createType19 = $Create.Array($$createType18);
