// Thin async wrappers over the Wails-bound methods. Every binding returns a
// Promise resolving to the JSON view from internal/gui. Centralizing the
// imports here keeps components decoupled from the generated bindings path
// (ui/bindings, produced by `wails3 generate bindings -b -noevents -names`)
// and gives one place to add error shaping later.
import {
  AddRelayProject,
	ApplyComposeRecipe,
  DeleteScript,
  ExportCapture,
  ExportTargets,
  ExportWebhook,
  GetScript,
  GetCapture,
  GetCaptureBody,
  GetSettings,
  GetWebhook,
  ListCaptures,
	ListComposeRecipes,
  ListScripts,
  ListSessions,
  ListWebhooks,
	FormatTransformFile,
	ParseTransformFile,
  RegisterRelay,
  RelayAdminAddProject,
  RelayAdminCreateClient,
  RelayAdminDeleteClient,
  RelayAdminDeleteProject,
  RelayAdminDeleteProfile,
  RelayAdminLoadProfile,
  RelayAdminOverview,
  RelayAdminProfiles,
  RelayAdminReassignProject,
  RelayAdminSaveProfile,
  RemoveRelayProject,
  ReplayWebhook,
  SaveScript,
  SaveSettings,
  SendComposedRequest,
  SetScriptEnabled,
  Status,
  TestScript,
} from "../bindings/github.com/plutack/wiretap/internal/gui/bindings.js";

export const api = {
  listWebhooks: (project = "") => ListWebhooks(project),
  getWebhook: (project, seq) => GetWebhook(project, seq),
  replayWebhook: (project, seq, targetURL) => ReplayWebhook(project, seq, targetURL),
  listCaptures: (sessionId = 0) => ListCaptures(sessionId),
  listSessions: (beforeID = 0, limit = 20) => ListSessions(beforeID, limit),
  getCapture: (id) => GetCapture(id),
  getCaptureBody: (id, part, limit) => GetCaptureBody(id, part, limit),
  status: () => Status(),
  listScripts: () => ListScripts(),
  getScript: (id) => GetScript(id),
  saveScript: (input) => SaveScript(input),
  setScriptEnabled: (id, enabled) => SetScriptEnabled(id, enabled),
  deleteScript: (id) => DeleteScript(id),
  testScript: (req) => TestScript(req),
	formatTransformFile: (input) => FormatTransformFile(input),
	parseTransformFile: (contents) => ParseTransformFile(contents),
  exportTargets: () => ExportTargets(),
  exportCapture: (id, target, client) => ExportCapture(id, target, client),
  exportWebhook: (project, seq, target, client) =>
    ExportWebhook(project, seq, target, client),
  getSettings: () => GetSettings(),
  saveSettings: (input) => SaveSettings(input),
  registerRelay: (input) => RegisterRelay(input),
  relayAdminOverview: (input) => RelayAdminOverview(input),
  relayAdminAddProject: (input) => RelayAdminAddProject(input),
  relayAdminCreateClient: (input) => RelayAdminCreateClient(input),
  relayAdminDeleteClient: (input) => RelayAdminDeleteClient(input),
  relayAdminDeleteProject: (input) => RelayAdminDeleteProject(input),
  relayAdminDeleteProfile: (id) => RelayAdminDeleteProfile(id),
  relayAdminLoadProfile: (id) => RelayAdminLoadProfile(id),
  relayAdminProfiles: () => RelayAdminProfiles(),
  relayAdminReassignProject: (input) => RelayAdminReassignProject(input),
  relayAdminSaveProfile: (input) => RelayAdminSaveProfile(input),
  addRelayProject: (project) => AddRelayProject(project),
  removeRelayProject: (project) => RemoveRelayProject(project),
  sendComposedRequest: (input) => SendComposedRequest(input),
	listComposeRecipes: () => ListComposeRecipes(),
	applyComposeRecipe: (input) => ApplyComposeRecipe(input),
};
