// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function GetWebhook(arg1:string,arg2:number):Promise<gui.WebhookView>;

export function ListCaptures():Promise<Array<gui.CaptureView>>;

export function ListWebhooks(arg1:string):Promise<Array<gui.WebhookView>>;

export function ReplayWebhook(arg1:string,arg2:number,arg3:string):Promise<gui.ReplayResult>;

export function Status():Promise<gui.StatusView>;
