// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function DeleteScript(arg1:number):Promise<void>;

export function GetScript(arg1:number):Promise<gui.ScriptView>;

export function GetWebhook(arg1:string,arg2:number):Promise<gui.WebhookView>;

export function ListCaptures():Promise<Array<gui.CaptureView>>;

export function ListScripts():Promise<Array<gui.ScriptView>>;

export function ListWebhooks(arg1:string):Promise<Array<gui.WebhookView>>;

export function ReplayWebhook(arg1:string,arg2:number,arg3:string):Promise<gui.ReplayResult>;

export function SaveScript(arg1:gui.ScriptInput):Promise<number>;

export function SetScriptEnabled(arg1:number,arg2:boolean):Promise<void>;

export function Status():Promise<gui.StatusView>;

export function TestScript(arg1:gui.ScriptTestRequest):Promise<gui.ScriptTestView>;
