// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScript(arg1) {
  return window['go']['gui']['Bindings']['DeleteScript'](arg1);
}

export function GetScript(arg1) {
  return window['go']['gui']['Bindings']['GetScript'](arg1);
}

export function GetCapture(arg1) {
  return window['go']['gui']['Bindings']['GetCapture'](arg1);
}

export function GetWebhook(arg1, arg2) {
  return window['go']['gui']['Bindings']['GetWebhook'](arg1, arg2);
}

export function ListCaptures() {
  return window['go']['gui']['Bindings']['ListCaptures']();
}

export function ListScripts() {
  return window['go']['gui']['Bindings']['ListScripts']();
}

export function ListWebhooks(arg1) {
  return window['go']['gui']['Bindings']['ListWebhooks'](arg1);
}

export function ReplayWebhook(arg1, arg2, arg3) {
  return window['go']['gui']['Bindings']['ReplayWebhook'](arg1, arg2, arg3);
}

export function SaveScript(arg1) {
  return window['go']['gui']['Bindings']['SaveScript'](arg1);
}

export function SetScriptEnabled(arg1, arg2) {
  return window['go']['gui']['Bindings']['SetScriptEnabled'](arg1, arg2);
}

export function Status() {
  return window['go']['gui']['Bindings']['Status']();
}

export function TestScript(arg1) {
  return window['go']['gui']['Bindings']['TestScript'](arg1);
}
