// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWebhook(arg1, arg2) {
  return window['go']['gui']['Bindings']['GetWebhook'](arg1, arg2);
}

export function ListCaptures() {
  return window['go']['gui']['Bindings']['ListCaptures']();
}

export function ListWebhooks(arg1) {
  return window['go']['gui']['Bindings']['ListWebhooks'](arg1);
}

export function ReplayWebhook(arg1, arg2, arg3) {
  return window['go']['gui']['Bindings']['ReplayWebhook'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['gui']['Bindings']['Status']();
}
